[package]
name = "ansible-vault"
description = "decrypt ansible vault 1.1 files"
version = "0.1.3"
authors = ["Wouter Geraedts <wouter@tweedegolf.com>"]
edition = "2018"
license = "MIT"
repository = "https://github.com/tweedegolf/ansible-vault-rs"

[dependencies]
base16 = "0.1.1"
hmac = "0.7.0"
sha2 = "0.8.0"
pbkdf2 = "0.3.0"
aes-ctr = "0.3.0"
block-padding = "0.1.0"
